module.exports = {
  plugins: [
    "@trivago/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  tailwindFunctions: ["cn"],
  importOrder: [
    "^react(.*)$",
    "^[A-Za-z](.*)$",
    "^@/assets(.*)$",
    "^@/modules(.*)$",
    "^@/layouts(.*)$",
    "^@/pages(.*)$",
    "^@/components(.*)$",
    "^@/store(.*)$",
    "^@/lib(.*)$",
    "^@/constants(.*)$",
    "^[./]*interfaces(.*)$",
    "^[./]*services(.*)$",
    "^[./]*stores(.*)$",
    "^[./]*components(.*)$",
    "^[./]*helpers(.*)$",
    "^[./]*constants(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  singleQuote: true,
};
